version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpu_essentials #名前が同じであれば実行できない可能性があるので、変更する
    ports:
      - "3000:3000"
    volumes: # PCのディレクトリをDockerにマウントしてアクセスできるようにする
      #- [PC側のpath]/[Docker側のpath]  (DockerからOpen Folderで開ける)
      - .:/app #Docker内でvscodeが立ち上がった際は/appが開く。
      - ../.cache:/root/.cache
      - /data1/shared:/shared
    tty: true
    shm_size: "4gb" #少ないとエラーが出ることがある
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] #利用できるGPUを指定したい場合
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA
                - video # NVDEC/NVENC/NVCUVID. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it

