sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -p https://github.com/zsh-users/zsh-syntax-highlighting \
    -p web-search \
    -p copypath \
    -p copyfile \
    -p copybuffer \
    -p dirhistory \
    -p history \
    -p history-substring-search \
    -p jsontools \
    -p macos \
    -p thefuck \
    -p fzf \
    -p https://github.com/fdellwing/zsh-bat \
    -p https://github.com/MichaelAquilina/zsh-you-should-use \
    -p https://github.com/marlonrichert/zsh-autocomplete