GPU_URL=""
USER_NAME="" 
USER_PASS="" 
MS_USER_NAME=""
MS_USER_PASS=""
PROXY_URL=""
PORT="8080"




export GPU_URL USER_NAME USER_PASS MS_USER_NAME MS_USER_PASS PROXY_URL PORT

echo "Environment variable set to:"
echo $GPU_URL $USER_NAME $USER_PASS $MS_USER_NAME $MS_USER_PASS $PROXY_URL $PORT
