GPU_URL=""
USER_NAME="" 
USER_PASS="" 
USER_TYPE="" 
USER_DEPARTMENT=""
DRIVE=""
MS_USER_NAME=""
MS_USER_PASS=""
PROXY_URL=""
PORT="8080"




export USER_NAME USER_PASS USER_TYPE USER_DEPARTMENT DRIVE MS_USER_NAME MS_USER_PASS PROXY_URL PORT

echo "Environment variable set to:"
echo $USER_NAME $USER_PASS $USER_TYPE $USER_DEPARTMENT $DRIVE $MS_USER_NAME $MS_USER_PASS $PROXY_URL $PORT
